### ISSUE TITLE
Cannot Install the Package

### ISSUE THREAD

**Issue by aj2620** [ianwaldrop/unity-package-installer#5]
[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/ianwaldrop/unity-package-installer.git]:
  Package unity-package-installer@https://github.com/ianwaldrop/unity-package-installer.git has invalid dependencies or related test packages:
    colors (dependency): Package [colors@1.1.2] cannot be found
    dive (dependency): Package [dive@0.5.0] cannot be found
    find-parent-dir (dependency): Version '^0.3.0' is invalid. Expected a 'SemVer' compatible value.
    mkdirp (dependency): Version '^0.5.1' is invalid. Expected a 'SemVer' compatible value.
    ncp (dependency): Version '^2.0.0' is invalid. Expected a 'SemVer' compatible value. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

// this is the error 

also tried installing the package from command prompt didnt work

**Comment by ianwaldrop** [comment]
thanks for creating an issue, but it's been a long time since this project has been updated. Now that unity has a first class package manager, which also uses npm, this is all but obsolete.

It looks like a dependency problem though—it's been 6 years, so some things might need to be updated.
